### ISSUE TITLE
massradius plot error

### ISSUE THREAD

**Issue by delinea** [pmaxted/pycheops#104]
When using the dataset.massradius function, the following error may occur when `verbose` is `True`:
<img width="994" alt="Screenshot 2020-05-11 at 17 55 19" src="https://user-images.githubusercontent.com/52831770/81582733-a92c4780-93b0-11ea-9ad5-9974eb6d4e8b.png">

After digging into the code, it seems that when the code "generates samples for input parameters not already sampled" (*pycheops/funcs.py*, line 735), a few sampled values might be negative even though this is physically impossible (K, m_star, etc.). This propagates as `NaN` into the code when computing other quantities using `log10` or `sqrt` and prevents the computation of mean and error values using `np.percentile` (*pycheops/utils.py*, line 60).

**Comment by pmaxted** [comment]
Added a fix in version 0.7.7 - this is now on the master branch.
Please install from the master branch on github and  check if this has worked for your example.

**Comment by pmaxted** [comment]
Added a fix in version 0.7.7 - this is now on the master branch.
Please install from the master branch on github and  check if this has worked for your example.

**Comment by delinea** [comment]
Fix works for cases where K has large uncertainties (compared to mean value). However, same errors occur if `r_star` (resp. `m_star`) has large uncertainty and `m_star` (resp. `r_star`) is not specified when calling `dataset.massradius()`.
Similar fix seems to be needed in _pycheops/dataset.py_ (lines 2018 and 2021) to solve the issue.

**Comment by pmaxted** [comment]
Agreed - this fix has been done and merged into the master branch.
 Please install (again) from the master branch on github and check if this has worked for your example.
-Pierre

**Comment by delinea** [comment]
New fix works fine. Thanks!
