### ISSUE TITLE
Issue with animate_frames

### ISSUE THREAD

**Issue by gbruno88** [pmaxted/pycheops#117]
On Python 3.8.3 and IPython 7.15.0, ubuntu 18.04

A matplotlib figure is opened, but no animation appears. These are the command and the output on terminal:

In [22]: dataset.animate_frames(nframes=10, imagette=False, subarray=True)      
Subarray data loaded from  /home/giovanni/Dropbox/CHEOPS-ST-GTO/pycheops_data/CH_PR100021_TG001801_V0100-SubArray.fits
HBox(children=(FloatProgress(value=0.0, max=8.0), HTML(value='')))

MovieWriter PillowWriter warning safe to ignore.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-cfd29e0a2a5d> in <module>
----> 1 dataset.animate_frames(nframes=10, imagette=False, subarray=True)

~/miniconda3/envs/pycheops/lib/python3.8/site-packages/pycheops/dataset.py in animate_frames(self, nframes, vmin, vmax, subarray, imagette, grid)
    812                 sub_anim = animation.ArtistAnimation(fig, frames, blit=True)
    813                 print("MovieWriter PillowWriter warning safe to ignore.")
--> 814                 sub_anim.save(title.replace(" ","")+'.gif', writer='PillowWriter')
    815                 with open(title.replace(" ","")+'.gif','rb') as file:
    816                     display(Image(file.read()))

~/miniconda3/envs/pycheops/lib/python3.8/site-packages/matplotlib/animation.py in save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs, progress_callback)
   1100                                          metadata=metadata)
   1101             else:
-> 1102                 alt_writer = next(writers, None)
   1103                 if alt_writer is None:
   1104                     raise ValueError("Cannot save animation: no writers are "

TypeError: 'MovieWriterRegistry' object is not an iterator

Thank you, 

Giovanni

**Comment by ThomasGWilson** [comment]
Hi Giovanni,

Thanks for highlighting this, what version of pycheops and matplotlib are you using?

Thanks,

Tom

**Comment by gbruno88** [comment]
Hi Tom,

Thanks for your reply. I'm using pycheops 0.7.8 (the last one, right?) and matplotlib 3.2.1.

Best,

Giovanni

**Comment by ThomasGWilson** [comment]
Hi Giovanni,

It looks like this is a known issue with matplotlib version 3.2.1 and the matplotlib team are apparently working on it with the fix apparently coming soon in version 3.2.2 or 3.3.0 of matplotlib: https://github.com/matplotlib/matplotlib/issues/16965

Thanks,

Tom

**Comment by gbruno88** [comment]
Hi Tom,

Thank you for pointing this out. I'll keep an eye on new releases of matplotlib.

Best,

Giovanni

**Comment by ThomasGWilson** [comment]
Hi Giovanni,

Not a problem. Please let me know if you notice that the new version is taking too long and I can try to think of a work around for PyCheops.

Thanks,

Tom

**Comment by gbruno88** [comment]
Hi Tom, 

Just to be sure: you're on a Mac, right? I was on a Mac a couple of years ago and noticed that matplotlib behaves slightly differently than on Linux.

Thanks, 

Giovanni

**Comment by ThomasGWilson** [comment]
Hi Giovanni,

No, I'm Ubuntu 18.04 as well. Although you raise a good point that in the future we may want to beta test pycheops on both Ubuntu and Mac.

Thanks,

Tom

**Comment by gbruno88** [comment]
I'm confused now: don't you encounter the same issue?

**Comment by ThomasGWilson** [comment]
On my main anaconda installation I'm running matplotlib version 3.1.3 so this doesn't seem to be an issue with old versions of the code.

**Comment by gbruno88** [comment]
That's interesting. Thanks.

**Comment by ThomasGWilson** [comment]
Hi Giovanni,

It looks like this bug has been fixed in the 3.2.2 version of matplotlib. Can you please upgrade your version and let me know if this has fixed it? 

Thanks,

Tom

**Comment by gbruno88** [comment]
Hi Tom, 

Thank you for letting me know. There seems to be a new error... It doesn't seem to be related to my code, but I don't understand what it might be due to.

dataset.animate_frames(nframes=10, imagette=False, subarray=True)
Subarray data loaded from  /home/giovanni/Dropbox/CHEOPS-ST-GTO/pycheops_data/CH_PR100002_TG015001_V0100-SubArray.fits
HBox(children=(FloatProgress(value=0.0, max=9.0), HTML(value='')))

*** TypeError: 'str' object is not callable

Cheers, 
Giovanni

**Comment by ThomasGWilson** [comment]
Hi Giovanni,

Yeah, that's not your code, but annoying a nomenclature change within the new version of matplotlib relating to animation writer function. I also found this last night and it should be fixed in the next version of PyCheops.

Cheers,

Tom

**Comment by gbruno88** [comment]
Sorry to hear that... Thank you for implementing the change!

Cheers,
Giovanni

**Comment by pmaxted** [comment]
Fixed in version 0.8.0
