### ISSUE TITLE
Trail plot of a single variable

### ISSUE THREAD

**Issue by delinea** [pmaxted/pycheops#130]
Using `pycheops.Dataset.trail_plot()` or `pycheops.Multivist.trail_plot()` with a single variable name (`len(plotkeys) == 1`) raises an Exception.
In the dataset.py and multivisit.py files (lines 1644 and 1117 respectively), the matplotlib figure is generated using `plt.subplots()`. When the number of subplots is 1, this function does not return a list anymore, but a single instance of AxesSubplot. This could be fixed either by setting `squeeze=False` in `plt.subplots()` and calling `ax[i, 0]` instead of `ax[i]`, or by writing something like `if n == 1: ax = [ax, ]`.
Thank you,
Adrien

**Comment by pmaxted** [comment]
Fixed in 0.8.4
