### ISSUE TITLE
T0 not being updated consistently when importing datasets with Multivisit

### ISSUE THREAD

**Issue by delinea** [pmaxted/pycheops#131]
When loading datasets with `pycheops.Multivisit`, the time reference `bjd_ref` is being set to the same value (=2457000) for all datasets. However, some objects or functions within each of the `pycheops.Multivisit.datasets` are not being updated leading to inconsistency in the stored data. I listed below the objects/functions that I found to be affected by this (some of them have the same issue origin):
- `dataset.emcee` MinimizerResult object not being fully updated (`params` is OK, but not `chain` nor `params_best`)
- `dataset.sampler` EnsembleSampler object not being updated (`backend`/`chain`/`get_chain()`)
- `dataset.diagnostic_plot()` not displaying correct BJD values
- `dataset.plot_lmfit()` not displaying correct BJD values
- `dataset.plot_emcee()` not displaying correct BJD values
- `dataset.trail_plot()` not displaying correct T_0 values
- `dataset.transit_noise_plot()` could be updated too (not necessary as no unit is displayed on the time axis)
Thank you,
Adrien

**Comment by pmaxted** [comment]
Updated T_0 consistently where possible. Did not attempt to fix T_0 values buried inside emcee sampler objects.
