### ISSUE TITLE
Celerite error for Multivisit TTV fit

### ISSUE THREAD

**Issue by mhooton** [pmaxted/pycheops#132]
Hi Pierre,

I recently got an error when running multivisit.fit_transit() with TTVs on the 12 transits we have of a Feature.Char target. A few detrend parameters were used in each of the analyses of the individual visits, but fit_transit ran successfully in a few hours with no TTVs and with T0 and P allowed to vary. But when I fixed T0 and P and changed ttv to true, emcee typically executes successfully for a few 10s of iterations, but then (I assume) prints the entire contents of the Multivisit object, and then gives the following error:

---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
<ipython-input-8-d90069275044> in <module>
      9                        f_s=f_s,
     10                        f_c=f_c,
---> 11                        burn=1024, steps=512, nwalkers=512) 

~/anaconda3/lib/python3.7/site-packages/pycheops/multivisit.py in fit_transit(self, steps, nwalkers, burn, T_0, P, D, W, b, f_c, f_s, h_1, h_2, ttv, ttv_prior, extra_priors, log_sigma_w, log_omega0, log_S0, log_Q, unroll, nroll, init_scale, progress)
    801             stdout.flush()
    802         pos, _, _ = sampler.run_mcmc(pos, burn, store=False, 
--> 803             skip_initial_state_check=True, progress=progress)
    804         sampler.reset()
    805         if progress:

~/anaconda3/lib/python3.7/site-packages/emcee/ensemble.py in run_mcmc(self, initial_state, nsteps, **kwargs)
    382 
    383         results = None
--> 384         for results in self.sample(initial_state, iterations=nsteps, **kwargs):
    385             pass
    386 

~/anaconda3/lib/python3.7/site-packages/emcee/ensemble.py in sample(self, initial_state, log_prob0, rstate0, blobs0, iterations, tune, skip_initial_state_check, thin_by, thin, store, progress)
    341 
    342                     # Propose
--> 343                     state, accepted = move.propose(model, state)
    344                     state.random_state = self.random_state
    345 

~/anaconda3/lib/python3.7/site-packages/emcee/moves/red_blue.py in propose(self, model, state)
     91 
     92             # Compute the lnprobs of the proposed position.
---> 93             new_log_probs, new_blobs = model.compute_log_prob_fn(q)
     94 
     95             # Loop over the walkers and update them accordingly.

~/anaconda3/lib/python3.7/site-packages/emcee/ensemble.py in compute_log_prob(self, coords)
    425                 map_func = map
    426             results = list(
--> 427                 map_func(self.log_prob_fn, (p[i] for i in range(len(p))))
    428             )
    429 

~/anaconda3/lib/python3.7/site-packages/emcee/ensemble.py in __call__(self, x)
    543     def __call__(self, x):
    544         try:
--> 545             return self.f(x, *self.args, **self.kwargs)
    546         except:  # pragma: no cover
    547             import traceback

~/anaconda3/lib/python3.7/site-packages/pycheops/multivisit.py in _log_posterior(pos, gps, lcs, models, modpars, noisemodel, priors, vn, return_fit)
    210         mod = model.eval(modpar, t=lc['time'])
    211         resid = lc['flux'] - mod
--> 212         lnprob += gp.log_likelihood(resid)
    213 
    214         if return_fit:

~/anaconda3/lib/python3.7/site-packages/celerite/celerite.py in log_likelihood(self, y, _const, quiet)
    177         resid = y - self.mean.get_value(self._t)
    178         try:
--> 179             self._recompute()
    180         except solver.LinAlgError:
    181             if quiet:

~/anaconda3/lib/python3.7/site-packages/celerite/celerite.py in _recompute(self)
    144                 raise RuntimeError("you must call 'compute' first")
    145             self.compute(self._t, self._yerr, check_sorted=False,
--> 146                          A=self._A, U=self._U, V=self._V)
    147 
    148     def _process_input(self, y):

~/anaconda3/lib/python3.7/site-packages/celerite/celerite.py in compute(self, t, yerr, check_sorted, A, U, V)
    135             beta_complex_real, beta_complex_imag,
    136             self._A, self._U, self._V,
--> 137             t, self._yerr**2
    138         )
    139         self.dirty = False

LinAlgError: failed to factorize or solve matrix

I'll note that I have successfully used the TTV feature without getting any errors for other (less computationally demanding) multivisit fits. Do you have any idea what might be wrong?

**Comment by pmaxted** [comment]
Please try to re-create this error and then run the following in your ipython notebook and send me the results...

%debug
print(alpha_real)
print(beta_real)
print(alpha_complex_real)
print(alpha_complex_imag)
print(beta_complex_real)
print(beta_complex_imag)
print(self._A)
print(self._U)
print(self._V)
print(t)
print(self._yerr)
print(self.kernel.jitter)

**Comment by mhooton** [comment]
The first time I reran it, it succesfully ran to completion and produced sensible outputs. The second time I reran it, I got the same error. Here are is the requested output:

> /Users/mhooton/anaconda3/lib/python3.7/site-packages/celerite/celerite.py(137)compute()
    135             beta_complex_real, beta_complex_imag,
    136             self._A, self._U, self._V,
--> 137             t, self._yerr**2
    138         )
    139         self.dirty = False

ipdb> print(alpha_real)
[]
ipdb> print(beta_real)
[]
ipdb> print(alpha_complex_real)
[1.55506364e+07 6.01812566e-03 6.01812566e-03 6.01812566e-03]
ipdb> print(alpha_complex_imag)
[3955867.56984595       0.               0.               0.        ]
ipdb> print(beta_complex_real)
[1.78358976e-07 0.00000000e+00 0.00000000e+00 0.00000000e+00]
ipdb> print(beta_complex_imag)
[7.01134591e-07 9.13908180e+01 1.82781636e+02 2.74172454e+02]
ipdb> print(self._A)
[]
ipdb> print(self._U)
[]
ipdb> print(self._V)
[]
ipdb> print(t)
[1988.92841953 1988.92911431 1988.92980908 1988.93050386 1988.93119864
 1988.9318934  1988.93258818 1988.93328296 1988.93397774 1988.9346725
 1988.93606206 1988.93675683 1988.9374516  1988.93814638 1988.93884115
 1988.93953593 1988.9402307  1988.94092547 1988.94162025 1988.94231503
 1988.94300981 1988.94370457 1988.94439935 1988.94509412 1988.9457889
 1988.94648367 1988.94717844 1988.94787322 1988.948568   1988.94926277
 1988.94995754 1988.95065232 1988.9513471  1988.95204186 1988.95343142
 1988.95412619 1988.95482096 1988.95621051 1988.95690529 1988.95760006
 1988.95829483 1988.95898961 1988.96037915 1988.96107393 1988.96176871
 1988.96246349 1988.96315825 1988.96385303 1988.96454781 1988.96524258
 1988.97635897 1988.97705374 1988.97774851 1988.97844329 1988.97913807
 1988.97983283 1988.98052761 1988.98122239 1988.98191716 1988.98261193
 1988.98330671 1988.98400149 1988.98469626 1988.98539104 1988.98608581
 1988.98678058 1988.98747536 1988.98817014 1988.9888649  1988.98955968
 1988.99025446 1988.99094923 1988.991644   1988.99233878 1988.99372833
 1988.9944231  1988.99511787 1988.99581265 1988.99650743 1988.99720219
 1988.99789697 1988.99859175 1988.99928652 1988.99998129 1989.00067607
 1989.00137084 1989.00345516 1989.00414994 1989.00484472 1989.00553948
 1989.00623426 1989.00692904 1989.00762382 1989.00831858 1989.00901336
 1989.00970814 1989.01040291 1989.01109768 1989.01179246 1989.01248723
 1989.01318201 1989.01387679 1989.01457155 1989.01526633 1989.01596111
 1989.01665588 1989.01735065 1989.01804543 1989.0187402  1989.01943498
 1989.02012975 1989.02082452 1989.0215193  1989.02221408 1989.02290884
 1989.02360362 1989.0242984  1989.02499317 1989.02568794 1989.02638272
 1989.02707749 1989.02777227 1989.02846704 1989.02916181 1989.02985659
 1989.03055137 1989.03124615 1989.03194091 1989.03263569 1989.03333047
 1989.03402524 1989.03472001 1989.03541479 1989.03610956 1989.03680434
 1989.0374991  1989.03819388 1989.03888866 1989.03958344 1989.0402782
 1989.04097298 1989.04375208 1989.04444685 1989.04514163 1989.04583641
 1989.04653117 1989.04722595 1989.04792073 1989.0486155  1989.04931027
 1989.05000505 1989.05069982 1989.0513946  1989.05208937 1989.05278414
 1989.05347892 1989.0541737  1989.05486847 1989.05625802 1989.05695279
 1989.05764757 1989.05834234 1989.05903711 1989.05973189 1989.06042667
 1989.06181621 1989.06251099 1989.06320576 1989.06390054 1989.06459531
 1989.06529008 1989.06598486 1989.06667964 1989.0673744  1989.06806918
 1989.06876396 1989.0701535  1989.07084828 1989.07154305 1989.07223783
 1989.0729326  1989.07362737 1989.07432215 1989.07571171 1989.07640647
 1989.07710125 1989.07779603 1989.0784908  1989.07918557 1989.07988034
 1989.08057512 1989.08196468 1989.08265944 1989.08335422 1989.084049
 1989.08474377 1989.08543854 1989.08613332 1989.08682809 1989.08752287
 1989.08821763 1989.08891241 1989.08960719 1989.09030197 1989.09099674
 1989.09169151 1989.09238629 1989.09308106 1989.09377584 1989.09447061
 1989.09516538 1989.09586016 1989.09655494 1989.09724971 1989.09794448
 1989.09863926 1989.09933403 1989.10002881 1989.10072358 1989.10141835
 1989.10211313 1989.10280791 1989.10350267 1989.10419745 1989.10489223
 1989.105587   1989.10628178 1989.10697655 1989.1083661  1989.10906089
 1989.10975564 1989.11045043 1989.11114521 1989.11183999 1989.11253476
 1989.11322953 1989.1139243  1989.11461908 1989.11531386 1989.11600862
 1989.1167034  1989.11739818 1989.11809296 1989.11878773 1989.1194825
 1989.12017727 1989.12087205 1989.12156683 1989.12226159 1989.12295637
 1989.12365115 1989.12573547 1989.12643024 1989.12712502 1989.1278198
 1989.12851456 1989.12920934 1989.1305989  1989.13129367 1989.13198844
 1989.13268321 1989.13337799 1989.13407277 1989.13476753 1989.13546231
 1989.13615709 1989.13685186 1989.13754664 1989.13824141 1989.13893618
 1989.13963096 1989.14032574 1989.1410205  1989.14171528 1989.14241006
 1989.14310484 1989.14379961 1989.14518915 1989.14588393 1989.14657871
 1989.14727349 1989.14796825 1989.14866303 1989.14935781 1989.15005258
 1989.15074735 1989.15144212 1989.1521369  1989.15283168 1989.15352646
 1989.15422122 1989.154916   1989.15561077 1989.15630555 1989.15700032
 1989.15769509 1989.15838987 1989.15908465 1989.15977943 1989.16047419
 1989.16116897 1989.16186374 1989.16255852 1989.1632533  1989.16394806
 1989.16464284 1989.16533762 1989.16603239 1989.16672716 1989.16742194
 1989.16811671 1989.16881149 1989.16950627 1989.17020103 1989.17089581
 1989.17159059 1989.17228536 1989.17298013 1989.17367491 1989.17436968
 1989.17506446 1989.17575924 1989.176454   1989.17714878 1989.17784356
 1989.17853833 1989.1792331  1989.17992788 1989.18062265 1989.18131743
 1989.18201221 1989.18270697 1989.18340175 1989.18409653 1989.1847913
 1989.18548608 1989.18618085 1989.18687562 1989.1875704  1989.18826518
 1989.18895994 1989.18965472 1989.1903495  1989.19104427 1989.19173905
 1989.19243382 1989.19312859 1989.19382337 1989.19451815 1989.19521292
 1989.19590769 1989.19660247 1989.19729724 1989.19799202 1989.19938156
 1989.20007634 1989.20077112 1989.20146589 1989.20216066 1989.20285543
 1989.20355021 1989.20424499 1989.20493975 1989.20563453 1989.20632931
 1989.20702408 1989.20771886 1989.20841363 1989.2091084  1989.20980318
 1989.21049796 1989.21119274 1989.2118875  1989.21258228 1989.21327705
 1989.21397183 1989.21466661 1989.21536137 1989.21605615 1989.21675093
 1989.2174457  1989.21814047 1989.21883525 1989.22508822 1989.22578299
 1989.22647777 1989.22717255 1989.22786731 1989.22856209 1989.22925687
 1989.22995164 1989.23134118 1989.23203596 1989.23273074 1989.23342552
 1989.23412029 1989.23481506 1989.23550983 1989.23689939 1989.23759417
 1989.23828893 1989.23898371 1989.23967848 1989.24037326 1989.24106803
 1989.2417628  1989.24245758 1989.24315236 1989.24384713 1989.2445419
 1989.24523668 1989.24593145 1989.24662623 1989.24732101 1989.24801577
 1989.24871055 1989.24940533 1989.2501001  1989.25079487 1989.25218442
 1989.2528792  1989.25357398 1989.25426874 1989.25496352 1989.2556583
 1989.25635307 1989.25704785 1989.25774261 1989.25843739 1989.25913217
 1989.25982695 1989.26052172 1989.26121649 1989.26191126 1989.26260604
 1989.26330082 1989.26399559 1989.26469036 1989.26538514 1989.26607991
 1989.26677469 1989.26746946 1989.26885901 1989.26955379 1989.27024856
 1989.27163811 1989.27233288 1989.27302766 1989.27372244 1989.2744172
 1989.27511198 1989.27580676 1989.27650153 1989.2771963  1989.27789107
 1989.27858585 1989.27928063 1989.27997541 1989.28067017 1989.28136495
 1989.28205972 1989.2827545  1989.28344928 1989.28414404 1989.28483882
 1989.2855336  1989.29526044 1989.29595521 1989.29664999 1989.29734476
 1989.29803953 1989.29873431 1989.29942909 1989.30012386 1989.30081863
 1989.30151341 1989.30220818 1989.30290296 1989.30359774 1989.3042925
 1989.30498728 1989.30568206 1989.30637683 1989.30707161 1989.30776637
 1989.30846115 1989.30915593 1989.3098507  1989.31054548 1989.31124025
 1989.31193502 1989.3126298  1989.31332458 1989.31401935 1989.31471412
 1989.3154089  1989.31610367 1989.31679845 1989.31749322 1989.31818799
 1989.31888277 1989.31957755 1989.32027232 1989.32096709 1989.32166186
 1989.32235664 1989.32305142 1989.3237462  1989.32444096 1989.32513574
 1989.32583051 1989.32652529 1989.32722007 1989.32791483 1989.32860961
 1989.32930439 1989.32999916 1989.33069394 1989.33138871]

ipdb> print(self._yerr)
[0.00094286 0.00094435 0.00094362 0.00094332 0.00094352 0.00094388
 0.00094329 0.00094421 0.00094605 0.00094634 0.0009476  0.00095086
 0.00095274 0.0009538  0.00095031 0.00094533 0.00094254 0.0009428
 0.00093992 0.00093868 0.00094045 0.00094296 0.00094672 0.00097706
 0.00098816 0.00098449 0.00098086 0.00098757 0.00099542 0.00100502
 0.00100857 0.00100881 0.00100923 0.00108269 0.00102789 0.00101644
 0.00102208 0.00095892 0.00096931 0.0009623  0.00094525 0.00094104
 0.00093275 0.00093153 0.00093201 0.00093169 0.00093337 0.00093177
 0.0009321  0.00093177 0.00093134 0.00093051 0.00093157 0.00093121
 0.00093147 0.00093234 0.00093351 0.00093241 0.00093264 0.00093289
 0.00093261 0.00093278 0.00093336 0.00093378 0.000933   0.00093363
 0.00093364 0.00093481 0.00093458 0.00093526 0.00093481 0.00093591
 0.00093611 0.00093708 0.00093816 0.00094005 0.00094048 0.0009404
 0.00094235 0.00094112 0.00094085 0.00094205 0.00094304 0.00094247
 0.00094303 0.00094355 0.00094486 0.00094723 0.00094851 0.00095219
 0.00095795 0.0009547  0.00094922 0.0009464  0.00094347 0.00094204
 0.00093998 0.00094115 0.00093873 0.00094146 0.00094591 0.0009788
 0.00098918 0.00098278 0.00098112 0.00098665 0.00099269 0.00099518
 0.00099381 0.0009937  0.00100415 0.00109021 0.00115247 0.00107378
 0.00104057 0.00102194 0.00099689 0.00095898 0.0009541  0.00095031
 0.0009427  0.00093784 0.00093436 0.00093269 0.00093241 0.00093132
 0.00093159 0.00093178 0.00093142 0.00093186 0.00093185 0.00093127
 0.00093115 0.00093091 0.00093098 0.00093033 0.00092884 0.00092821
 0.00093144 0.00092842 0.0009304  0.00093199 0.00093043 0.00093031
 0.00093057 0.00093065 0.00093176 0.00093186 0.00093242 0.00093164
 0.00093177 0.00093197 0.00093321 0.00093278 0.00093261 0.00093335
 0.00093354 0.00093308 0.00093417 0.00093429 0.00093475 0.00093465
 0.00093494 0.00093564 0.00093652 0.00093747 0.00093752 0.00093783
 0.00093884 0.00093876 0.0009382  0.00093792 0.00093791 0.000938
 0.00093748 0.00093785 0.00094063 0.00094219 0.00094179 0.00094271
 0.00094083 0.0009432  0.00094831 0.0009548  0.0009529  0.00094642
 0.00093992 0.00093938 0.00093775 0.00093484 0.00093406 0.00093876
 0.00097521 0.00098896 0.00099114 0.00099113 0.00099482 0.00099468
 0.00099331 0.00099727 0.00100205 0.00099877 0.00101615 0.00109088
 0.00108035 0.00103387 0.00100421 0.00096437 0.00093938 0.00093534
 0.00093452 0.00093443 0.00093165 0.00092858 0.00092753 0.00092644
 0.00092629 0.00092608 0.00092567 0.00092579 0.0009258  0.00092482
 0.00092554 0.00092667 0.00092542 0.0009251  0.00092486 0.00092573
 0.00092571 0.00092535 0.00092467 0.00092466 0.0009251  0.000925
 0.00092468 0.00092491 0.00092446 0.00092504 0.00092546 0.00092581
 0.00092623 0.00092714 0.00092645 0.00092674 0.0009267  0.00092635
 0.00092686 0.00092813 0.00092771 0.00092726 0.00092762 0.00092833
 0.00092884 0.00092945 0.00093019 0.00093146 0.00093063 0.00093236
 0.00093312 0.00093344 0.00093425 0.00093534 0.00093528 0.00093448
 0.00093675 0.00093731 0.00093794 0.00093822 0.00093832 0.00093886
 0.00093825 0.00093833 0.00094012 0.00094024 0.00094316 0.00094541
 0.00094929 0.00094772 0.00094476 0.00094222 0.00093977 0.000937
 0.00093384 0.0009348  0.00093589 0.00093966 0.00097168 0.0009867
 0.00099292 0.00098783 0.00099217 0.0009942  0.00099521 0.0009958
 0.00100987 0.00103047 0.00102362 0.00100765 0.00101168 0.00102819
 0.00102237 0.00097362 0.00094795 0.00093591 0.00093318 0.00093307
 0.00093202 0.00093311 0.00093225 0.0009316  0.0009309  0.00093127
 0.00093104 0.00093111 0.0009312  0.00093094 0.00093115 0.00093131
 0.0009303  0.00093085 0.00093059 0.00093062 0.00093126 0.00093086
 0.00093111 0.00093117 0.00093078 0.00093075 0.00093053 0.00092989
 0.00093058 0.00093039 0.00093013 0.00093069 0.00093157 0.00093165
 0.00093239 0.00093176 0.00093199 0.00093222 0.00093253 0.00093232
 0.00093213 0.00093329 0.00093255 0.00093282 0.0009337  0.00093374
 0.00093429 0.00093452 0.00093446 0.00093492 0.00093545 0.00093551
 0.00093705 0.00093789 0.00093932 0.00094036 0.00094019 0.00094032
 0.0009399  0.00094098 0.00094209 0.00094298 0.00094333 0.00094402
 0.00094225 0.00094309 0.00094306 0.00094324 0.00094539 0.00095049
 0.00095502 0.00095893 0.00095813 0.00095682 0.00095125 0.00094366
 0.00094215 0.00094159 0.00093984 0.0009396  0.00094244 0.00100515
 0.00100058 0.00100562 0.00101363 0.00101676 0.00102385 0.00102512
 0.00102864 0.00095086 0.00094239 0.00093604 0.00093567 0.00093549
 0.00093413 0.00093502 0.00093227 0.00093215 0.00093185 0.0009312
 0.00093057 0.0009301  0.0009307  0.00093067 0.0009317  0.00093091
 0.00093026 0.00093034 0.00093059 0.00093072 0.00093087 0.00093161
 0.00093054 0.00093118 0.00093073 0.0009301  0.00093061 0.00093072
 0.00093095 0.00093121 0.00093147 0.00093187 0.00093152 0.00093215
 0.00093236 0.00093262 0.00093245 0.00093247 0.00093346 0.00093316
 0.00093323 0.00093355 0.00093384 0.00093361 0.00093453 0.00093456
 0.00093404 0.00093495 0.0009353  0.00093633 0.00093804 0.00093883
 0.00094035 0.00093997 0.0009407  0.00094078 0.00094078 0.00094034
 0.00094223 0.00094292 0.000944   0.00094362 0.00094303 0.00094259
 0.00094631 0.00095022 0.00095337 0.00095952 0.00095817 0.00095479
 0.00094937 0.00094439 0.00094183 0.00094181 0.001008   0.00099546
 0.00099066 0.00099695 0.00099984 0.00098812 0.00094678 0.00094381
 0.00093845 0.0009351  0.00093401 0.00093414 0.00093297 0.00093282
 0.00093371 0.00093602 0.00093403 0.00093213 0.00093127 0.00093154
 0.000931   0.00093084 0.0009304  0.00093054 0.0009305  0.00093016
 0.0009305  0.00093069 0.00093069 0.00093079 0.00093093 0.00092987
 0.00092984 0.00093047 0.00092966 0.00093083 0.00092826 0.00093074
 0.00093094 0.00093161 0.00093177 0.00093188 0.00093142 0.00093129
 0.00093189 0.00093391 0.00093239 0.00093251 0.00093323 0.00093244
 0.00093281 0.00093307 0.00093363]
ipdb> print(self.kernel.jitter)
2.900607001636408e-07

**Comment by pmaxted** [comment]
My guess is that this is a case of the hyperparameters of the noise models
(log_omega0, log_S0) going to extreme values that are causing numerical
problems. Do you have any priors set on these values?
Regards,
 -Pierre

**Comment by mhooton** [comment]
I have:
log_omega0=ufloat(4.3,0.6),
log_S0=ufloat(-22.3,0.6),
which I think are probably the values from the notebook demonstrating the TTVs in the tutorial.

**Comment by pmaxted** [comment]
This issue thought to be a numerical stability issue with celerite - should be fixed in 0.9.1 which uses celerite2
