### ISSUE TITLE
Read datasets into multivisit object in a logical order

### ISSUE THREAD

**Issue by mhooton** [pmaxted/pycheops#133]
Hi Pierre,

Currently, the order in which datasets are read and stored in the multivisit object appears to be at the whims of glob.glob, which e.g. means that the light curves in the plot_fits can be arranged with no logical order to them. Could this be changed to store them in, say, chronological order? I did a workaround for my local copy by changing glob(ptn) to sorted(glob(ptn)), but a more robust way might be by sorting the datasets by the first time in the light curve or table.

**Comment by ThomasGWilson** [comment]
Hi Matthew,

Good idea. I've included a couple of lines to sort the imported datasets by their bjd_ref. This should be in v0.8.2.

Thanks,

Tom

**Comment by pmaxted** [comment]
Fixed in 0.8.2
