### ISSUE TITLE
`massradius`: avoid download TEPCAT file if server is down

### ISSUE THREAD

**Issue by lucaborsato** [pmaxted/pycheops#137]
I cannot run the `massradius` function because it cannot download an updated version of the TEPCAT file (`/jkt/tepcat/allplanets-csv.csv`) from www.astro.keele.ac.uk that is currently unreachable.

Could be possible to add a check if the server is down (e.g. with a `try: except:`) so it can skip the error?
Or add an input keyword that avoid tepcat to be downloaded.
Luca

**Comment by pmaxted** [comment]
Fixed in 0.8.4
