### ISSUE TITLE
Negative residual offset in `pycheops.MultiVisit.plot_fit`

### ISSUE THREAD

**Issue by delinea** [pmaxted/pycheops#139]
Hi Pierre, Tom,

`pycheops.MultiVisit.plot_fit` does not take into account negative values of the parameter `res_offset`, in order to place the residual curves in chronological order from top to bottom in the plot.
I think changing the line 1391 of the file *multivisit.py* from `if roff > 0:` to `if roff != 0:` would do the trick.

Thanks,
Adrien

**Comment by ThomasGWilson** [comment]
Hi Adrien,

In the newest version of pycheops (v0.8.3) visits should be loaded in a chronological order by default. If this is not the case, I'll look into it. Can you confirm you're using the newest version?

Thanks,

Tom

**Comment by delinea** [comment]
Hi Tom,

Yes I am using version 0.8.3, and the datasets are indeed loaded in chronological order.
I realise I made a mistake explaining the problem, sorry.
**It is** possible to give a negative value for `res_offset` in `pycheops.MultiVisit.plot_fit`, but it messes with the vertical scaling.
Changing the line 1391 in the file *multivisit.py* from `if roff > 0:` to `if roff != 0:` should solve this minor issue.

Thanks,
Adrien

**Comment by ThomasGWilson** [comment]
Hi Adrien,

Ok, I see it now. Thanks for letting us know, it should be fixed in the next update.

If you want to edit your own code, making the change you suggested does work, but then below that if/else statement you should also add:

        if roff < 0:
            ax[1].set_ylim(ax[1].get_ylim()[::-1])

To flip the y-axis of the residuals.

Cheers,
Tom

**Comment by delinea** [comment]
Hi Tom,
Yes you're right, the y-axis is flipped when `res_offset < 0`.
To keep it short, one can do something like:
`if roff !=0: ax[1].set_ylim(np.sort([-0.75*roff, roff*(n-0.25)]))`
Cheers,
Adrien

**Comment by pmaxted** [comment]
Fixed in 0.8.4
