### ISSUE TITLE
update of prefixes in TransitModel in models.py

### ISSUE THREAD

**Issue by jcabrera271828** [pmaxted/pycheops#141]
Dear Pierre,

I figured out that there might be an issue in 'models.py' in the class TransitModel(Model). When defining the hints (def _set_paramhints_prefix(self)) there are some expressions missing the prefix. For example:
self.set_param_hint('e',min=0,max=1,expr='f_c**2 + f_s**2') should 
probably should rather read:
self.set_param_hint('e',min=0,max=1,expr='{p:s}f_c**2 + {p:s}f_s**2'.format(p=self.prefix))

The same would be true for q_1, q_2, and k, namely:
self.set_param_hint('q_1',min=0,max=1,expr='(1-{p:s}h_2)**2'.format(p=self.prefix))
self.set_param_hint('q_2',min=0,max=1,expr='({p:s}h_1-{p:s}h_2)/(1-{p:s}h_2)'.format(p=self.prefix)) 
self.set_param_hint('{p:s}k'.format(p=self.prefix), expr=expr, min=0, max=0.5)

MODEL = TransitModel( prefix='pl6d_')
parameters    = MODEL.make_params()
print( parameters)

Best regards
Juan

**Comment by pmaxted** [comment]
Fixed in 0.8.4
