### ISSUE TITLE
valid values for limb darkening coefficients in TransitModel from models.py

### ISSUE THREAD

**Issue by jcabrera271828** [pmaxted/pycheops#142]
Dear Pierre,

I am using the class TransitModel from models.py to model primary transits.

I realize that I am configuring as inputs for the modellig the limb-darkening parameters h_1 and h_2 (which are the output from tools like stagger_power2_interpolator from ld.py). 

However, the transit function (_transit_func in TransitModel) works with q1=(1-h_2)^2 and q2=(h_1-h_2)/(1-h_2) instead. The issue is that _transit_func returns ones (no transit at all) when q2<=0 or q2>=1 (same for q1) which was unexpected. I admit that such limb darkening values might be unconventional, but sometimes it could happen (well, this is how I found out :).

Which are the physical criteria used to define the limits of q1 and q2? Could we rather implement them in the log likelyhood function rather than hard implementing them in TransitModel? Thanks in advance!

Best regards
Juan

**Comment by pmaxted** [comment]
Dear Juan,
 these limits are required to avoid negative fluxes. See Short et al.
 https://ui.adsabs.harvard.edu/abs/2019RNAAS...3..117S/abstract
Regards,
 -Pierre
