### ISSUE TITLE
dataset.view_report() doesn't work for simulated datasets

### ISSUE THREAD

**Issue by mhooton** [pmaxted/pycheops#146]
I get the following error:

    124     if view_report:
--> 125         dataset.view_report()
    126     if animate_imagettes:
    127         subarray = False

~/anaconda3/lib/python3.7/site-packages/pycheops/dataset.py in view_report(self, pdf_cmd, configFile)
    828             report = list(filter(r.match, self.list))
    829             if len(report) == 0:
--> 830                 raise Exception('Dataset does not contain DRP report.')
    831             if len(report) > 1:
    832                 raise Exception('Multiple reports in datset')

Exception: Dataset does not contain DRP report.

Feel free to test on simulation number 8241, for which I'm getting the error.

**Comment by pmaxted** [comment]
Use the keyword option view_report_on_download=False to avoid this error.
-Pierre

**Comment by mhooton** [comment]
All the simulated datasets I've had previous have had a report. I think they may have changed its location in the folder structure fairly recently.

**Comment by ThomasGWilson** [comment]
Ok, got it. Try adding the following to your local dataset.from_simulation on line 506 of dataset.py (i.e. just before tgzPath = Path(_cache_path,file_key).with_suffix('.tgz')):

        pdfFile = "{}_DataReduction.pdf".format(file_key)
        pdfPath = Path(_cache_path,pdfFile)
        if pdfPath.is_file():
            if verbose: print('{} already downloaded'.format(pdfFile))
        else:
            _re = re.compile(r'CH_.*RPT_COR_DataReduction.*pdf')
            pdffiles = list(filter(_re.match, filelist))
            if len(pdffiles) > 0: 
                cmd = 'RETR {}'.format(pdffiles[0])
                if verbose: print('Downloading {} ...'.format(pdfFile))
                ftp.retrbinary(cmd, open(str(pdfPath), 'wb').write)
        ftp.quit()

This has retrieved the PDF report for me.

**Comment by mhooton** [comment]
Works beautifully, thank you.

**Comment by ThomasGWilson** [comment]
I'll include it in the next update.
