### ISSUE TITLE
Problem with installing version 0.9.1

### ISSUE THREAD

**Issue by gbruno88** [pmaxted/pycheops#149]
Hello,

I have a problem with the installation, which seems to be related to celerite2 and the fact that it uses PEP 517 to build the relative wheel. I have PEP 517 installed, and the last version of pip (20.2.3) on Ubuntu 18.04. I have found some discussions on internet about the problem with PEP, such as 

https://github.com/pypa/pip/issues/6222
https://stackoverflow.com/questions/61365790/error-could-not-build-wheels-for-scipy-which-use-pep-517-and-cannot-be-installe

but I haven't been able to solve it
Please find the log below.

Thank you, 
Giovanni

`Collecting celerite2
  Using cached celerite2-0.0.0.tar.gz (827 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.13.0 in ./miniconda3/envs/pycheops/lib/python3.8/site-packages (from celerite2) (1.18.5)
Building wheels for collected packages: celerite2
  Building wheel for celerite2 (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/giovanni/miniconda3/envs/pycheops/bin/python3.8 /home/giovanni/miniconda3/envs/pycheops/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpepils1fz
       cwd: /tmp/pip-install-3lciq_9z/celerite2
  Complete output (63 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/celerite2
  copying python/celerite2/testing.py -> build/lib.linux-x86_64-3.8/celerite2
  copying python/celerite2/ext.py -> build/lib.linux-x86_64-3.8/celerite2
  copying python/celerite2/celerite2_version.py -> build/lib.linux-x86_64-3.8/celerite2
  copying python/celerite2/celerite2.py -> build/lib.linux-x86_64-3.8/celerite2
  copying python/celerite2/__init__.py -> build/lib.linux-x86_64-3.8/celerite2
  copying python/celerite2/terms.py -> build/lib.linux-x86_64-3.8/celerite2
  creating build/lib.linux-x86_64-3.8/celerite2/jax
  copying python/celerite2/jax/celerite2.py -> build/lib.linux-x86_64-3.8/celerite2/jax
  copying python/celerite2/jax/__init__.py -> build/lib.linux-x86_64-3.8/celerite2/jax
  copying python/celerite2/jax/terms.py -> build/lib.linux-x86_64-3.8/celerite2/jax
  copying python/celerite2/jax/ops.py -> build/lib.linux-x86_64-3.8/celerite2/jax
  creating build/lib.linux-x86_64-3.8/celerite2/torch
  copying python/celerite2/torch/celerite2.py -> build/lib.linux-x86_64-3.8/celerite2/torch
  copying python/celerite2/torch/__init__.py -> build/lib.linux-x86_64-3.8/celerite2/torch
  copying python/celerite2/torch/terms.py -> build/lib.linux-x86_64-3.8/celerite2/torch
  copying python/celerite2/torch/ops.py -> build/lib.linux-x86_64-3.8/celerite2/torch
  creating build/lib.linux-x86_64-3.8/celerite2/theano
  copying python/celerite2/theano/celerite2.py -> build/lib.linux-x86_64-3.8/celerite2/theano
  copying python/celerite2/theano/__init__.py -> build/lib.linux-x86_64-3.8/celerite2/theano
  copying python/celerite2/theano/terms.py -> build/lib.linux-x86_64-3.8/celerite2/theano
  copying python/celerite2/theano/ops.py -> build/lib.linux-x86_64-3.8/celerite2/theano
  running egg_info
  writing python/celerite2.egg-info/PKG-INFO
  writing dependency_links to python/celerite2.egg-info/dependency_links.txt
  writing requirements to python/celerite2.egg-info/requires.txt
  writing top-level names to python/celerite2.egg-info/top_level.txt
  reading manifest file 'python/celerite2.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching '.*'
  warning: no previously-included files matching '.gitignore' found under directory '*'
  no previously-included directories found matching 'c++/test'
  no previously-included directories found matching '.github'
  writing manifest file 'python/celerite2.egg-info/SOURCES.txt'
  copying python/celerite2/backprop.cpp -> build/lib.linux-x86_64-3.8/celerite2
  copying python/celerite2/driver.cpp -> build/lib.linux-x86_64-3.8/celerite2
  copying python/celerite2/driver.hpp -> build/lib.linux-x86_64-3.8/celerite2
  running build_ext
  creating tmp
  gcc -pthread -B /home/giovanni/miniconda3/envs/pycheops/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/giovanni/miniconda3/envs/pycheops/include/python3.8 -c /tmp/tmph7tm4c9x.cpp -o tmp/tmph7tm4c9x.o -std=c++17
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -B /home/giovanni/miniconda3/envs/pycheops/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/giovanni/miniconda3/envs/pycheops/include/python3.8 -c /tmp/tmpmjsxeayq.cpp -o tmp/tmpmjsxeayq.o -fvisibility=hidden
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  building 'celerite2.driver' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/python
  creating build/temp.linux-x86_64-3.8/python/celerite2
  gcc -pthread -B /home/giovanni/miniconda3/envs/pycheops/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ic++/include -Ic++/vendor/eigen -Ipython/celerite2 -I/tmp/pip-build-env-ib8qvryl/overlay/lib/python3.8/site-packages/numpy/core/include -I/tmp/pip-build-env-ib8qvryl/overlay/lib/python3.8/site-packages/pybind11/include -I/tmp/pip-build-env-ib8qvryl/overlay/lib/python3.8/site-packages/pybind11/include -I/home/giovanni/miniconda3/envs/pycheops/include/python3.8 -c python/celerite2/driver.cpp -o build/temp.linux-x86_64-3.8/python/celerite2/driver.o -DVERSION_INFO="0.0.0" -std=c++17 -fvisibility=hidden
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  g++ -pthread -shared -B /home/giovanni/miniconda3/envs/pycheops/compiler_compat -L/home/giovanni/miniconda3/envs/pycheops/lib -Wl,-rpath=/home/giovanni/miniconda3/envs/pycheops/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/python/celerite2/driver.o -o build/lib.linux-x86_64-3.8/celerite2/driver.cpython-38-x86_64-linux-gnu.so
  building 'celerite2.backprop' extension
  gcc -pthread -B /home/giovanni/miniconda3/envs/pycheops/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ic++/include -Ic++/vendor/eigen -Ipython/celerite2 -I/tmp/pip-build-env-ib8qvryl/overlay/lib/python3.8/site-packages/numpy/core/include -I/tmp/pip-build-env-ib8qvryl/overlay/lib/python3.8/site-packages/pybind11/include -I/tmp/pip-build-env-ib8qvryl/overlay/lib/python3.8/site-packages/pybind11/include -I/home/giovanni/miniconda3/envs/pycheops/include/python3.8 -c python/celerite2/backprop.cpp -o build/temp.linux-x86_64-3.8/python/celerite2/backprop.o -DVERSION_INFO="0.0.0" -std=c++17 -fvisibility=hidden
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc: internal compiler error: Killed (program cc1plus)
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
  error: command 'gcc' failed with exit status 4
  ----------------------------------------
  ERROR: Failed building wheel for celerite2
Failed to build celerite2
ERROR: Could not build wheels for celerite2 which use PEP 517 and cannot be installed directly
`

**Comment by pmaxted** [comment]
Dear Giovanni,
 have you tried running "pip install celerite2" before upgrading?
 Regards,
 -Pierre

________________________________

**Comment by pmaxted** [comment]
This is a problem with celerite2 - issue raised on DFM's github page
