### ISSUE TITLE
MultiVisit with and without gp changes value of the T_0 in a different way

### ISSUE THREAD

**Issue by lucaborsato** [pmaxted/pycheops#153]
Loading dataset with MultiVisit should change the T_0 in params in a consistent way (adding bjd_ref and removing 2457000).
I found that if the dataset has no gaussian process the T_0 values will be modified in a different way with respect to the case with gaussian process.

I attached a zip file with the notebook that reproduces the issue and the two datasets.
[MultiVisit_issue.zip](https://github.com/pmaxted/pycheops/files/5267044/MultiVisit_issue.zip)

**Comment by pmaxted** [comment]
Issue could not be reproduced -closing.
