### ISSUE TITLE
Simultaneous fit of linear ephemeris and single T_0 with MultiVisit

### ISSUE THREAD

**Issue by lucaborsato** [pmaxted/pycheops#154]
At the moment the MultiVisit class can:
- fit the linear ephemeris only (with `ttv=False`) 
or
- fit the TTV (ttv=True) with fixed linear ephemeris.

I suggest a one-step fit with two log-likelihood (lnL):
- lnL_lin from the model with ttv=False, so each T_0 comes from the linear ephemeris, that is like a folded model;
- lnL_fit where the T_0 are fitted, as in the single visit analysis (the T_0 parameters could be load from previous dataset and used as initial points).

The final lnL will be the composition of both, something like lnL = lnL_lin + lnL_fit.
In this way we are assuming with lnL_lin that the light-curves have a periodicity and we can compute the linear ephemeris (Tref and Pref), but at the same time we know that each visit has its own T_0.

I know that this is more time consuming, but I suggest this because the two-step (1) ttv=False, (2) ttv=True, it is not correct from a statistical point of view, and then because in this way we have improved single T_0s (with errors) and also the best common transit parameters.

**Comment by pmaxted** [comment]
Dear Luca,

 If you do a fit with ttv=false then each T_0 comes from the linear ephemeris, so I think this is already the case lnL_lin.

 If you do a fit with ttv=True then each T_0 is a free parameter. For convenience I reparametrize the problem so that the time of mid-transit for dataset i is T_0,i = T_0 + P*cycle_i + ttv_i. This seems to me to be the case lnL_fit.

 Is your motivation to get a robust estimate on the errors for T_0 and P for a linear ephemeris fit?

Regards,
 -Pierre

________________________________

**Comment by lucaborsato** [comment]
Dear Pierre,
yes I would like to have a robust estimate of the linear ephemeris and at the same time of the single T0s with errors.
The 2-step fit should be avoided in most of the cases.
I tested your parmaterization simultaneously fitting lin. ephem. and the ttv_i, but if the initial lin. eph. is old (that is the case of many warm-Jupiter discovered with WASP) the fit will never converge. If you do the 2-lnL way, that is fit lin. eph. and the T0s values (not the ttv_i, ma the T0_i) it converges (but I know that it is time consuming).

Regards,
Luca

**Comment by pmaxted** [comment]
Dear Luca,
 did you try updating the linear ephemeris before doing Multivisit using the times of mid-transit from the analysis of the individual transits with pycheops.Dataset?

The plan would then be ....

  1.  Fit individual transits with Dataset.fit_transit
  2.  Update T_0 and P fitting times of mid-transit from step 1 plus published data
  3.  Multivisit.fit_transit with ttv=True, T_0 and P fixed from step 2.
  4.  Use results of step 3 to calculate new times of mid-transit and their errors (and covariance?)
  5.  Fit times of mid-transit from step 4 plus published times to test for dP/dt or other models for TTV

In step 5 you can use the covariance matrix from step 4 to calculate the likelihood if you are worried about correlations between these measurements.

https://en.wikipedia.org/wiki/Multivariate_normal_distribution#Likelihood_function

Regards,
 -Pierre
________________________________

**Comment by pmaxted** [comment]
No fix required.
