### ISSUE TITLE
Inconsitent default value for logQ in Multivisit

### ISSUE THREAD

**Issue by delinea** [pmaxted/pycheops#155]
Looking into the code, I noticed that the default value of `log Q` in `pycheops.multivisit.MultiVisit.__make_noisemodel__` is `1/sqrt(2)`, hence inconsistent with the default (supposedly correct) value in `pycheops.dataset.Dataset.emcee_sampler`, where `log Q = log(1/sqrt(2))`.

To be fully explicit, the Multivisit GP thus considers the default quality factor to be `Q = exp(1/sqrt(2))`.

Regards,
Adrien

**Comment by pmaxted** [comment]
Fixed in 0.9.2
