### ISSUE TITLE
Bayes factors computation of d2fdt2 doesn't seem to be computed

### ISSUE THREAD

**Issue by odemangeon** [pmaxted/pycheops#159]
Within the WG4 (Atmo.CHAR), there has been some discussion about the detrending v. time of the eclipse data. We are discussing whether or not we should detrend against d2fdt2. The reason is that for some datasets, the fitted eclipse depth varies relatively significantly if we detrend against d2fdt2 or not. I thought to use the new Bayes factors computation to decided whether or not the data support the detrending against d2fdt2.

The problem is that even when detrending against this parameter
`result_lmfit = dst.lmfit_eclipse(T_0=T_0, P=P, D=D, W=W, b=b,`
`                                L=(0.00001,0.001),`
`                                f_c=f_c, f_s=f_s, a_c=a_c,`
`                                 dfdsinphi=dprior,dfdcosphi=dprior,`
`                                dfdsin2phi=dprior,dfdcos2phi=dprior,`
`                                dfdsin3phi=dprior,dfdcos3phi=dprior,`
`                                 dfdt=dprior, d2fdt2=dprior,dfdcontam=dprior,`
`                                )`
The output doesn't display the Bayes factor for d2fdt2, it's only shown for dfdt. Here is the output of `dst.lmfit_report(min_correl=0.5)`
[[Bayes Factors]]  (values >~1 => free parameter probably not useful)
    dfdcontam:         0.764
    dfdt:              0.779
    dfdsinphi:         1.494
    dfdcosphi:         1.016
    dfdsin2phi:        0.601
    dfdcos2phi:        1.846
    dfdsin3phi:        1.548
    dfdcos3phi:        1.171

**Comment by odemangeon** [comment]
Thanks for the fast feedback @pmaxted. That solved it. 
For me the issue is closed, but I let you close it when you want.

**Comment by pmaxted** [comment]
Fixed in version 0.9.3
