### ISSUE TITLE
cannot import name 'Dace' from 'dace' (unknown location)

### ISSUE THREAD

**Issue by LuisaMaria** [pmaxted/pycheops#160]
not sure what is going on, but this happens when I try to download data from the database...

**Comment by ThomasGWilson** [comment]
Hi Luisa,

Did you recently update the DACE API? Others have had this issue after a DACE update.

Cheers,

Tom

**Comment by LuisaMaria** [comment]
I did it, indeed.
And of course it doesn't recognize Cheops as module...

**Comment by ThomasGWilson** [comment]
Hi Luisa,

Did you upgrade using; pip install dace --upgrade?

If so, try this command instead; pip install --index-url https://dace.unige.ch/api python-dace-client --upgrade

That might fix it.

Cheers,
Tom

**Comment by LuisaMaria** [comment]
I did it like that, but it is already up to date...

**Comment by pmaxted** [comment]
This looks like a problem with the DACE API. Please report this problem to julien.burnier@unige.ch
Regards,
 -Pierre
________________________________

**Comment by pmaxted** [comment]
Not a pycheops issue - closing.
