### ISSUE TITLE
Add 'SMEARING_LC' to dataset.lightcurve 

### ISSUE THREAD

**Issue by sergiohoyer** [pmaxted/pycheops#165]
Since v12 of the DRP the column "SMEARING_LC" is delivered in the light curve file.
The **SMEARING_LC** column is already subtracted from the FLUX but the correction can be reversed by simply adding the smear column to the flux again.   It can be also useful for the decorrelation analysis.

Cheers,

Sergio

**Comment by pmaxted** [comment]
Added in 0.9.4
