### ISSUE TITLE
emcee backend (HDF)

### ISSUE THREAD

**Issue by lucaborsato** [pmaxted/pycheops#169]
Hi,
I am wondering if it would be possible to pass an emcee backend object as argument to emcee_sampler method of Dataset.
This would help to re-analyse posterior distribution without running emcee again or keeping a notebook open.
I think the user should provide the object as:
```
filename = 'user_defined_filename_with_extension.hdf5'
backend = emcee.backends.HDFBackend(filename)
backend.reset(nwalkers, ndim)
results = dataset.emcee_sampler(..., backend=backend)
```

Ref.: [https://emcee.readthedocs.io/en/stable/tutorials/monitor/](https://emcee.readthedocs.io/en/stable/tutorials/monitor/)

Best,
Luca

**Comment by pmaxted** [comment]
Does this add anything compared to dataset.save() and dataset.load()? I think everything you need will be stored in dataset.sampler and/or dataset.emcee

**Comment by lucaborsato** [comment]
The backend allows the user to continue a previous analysis.
If the chains did not reach the convergence we can load the backend and continue the run from the last step.
Furthermore I found that the pickle package does not ensure compatibility with future versions (of pickle and python).
Best,
Luca

**Comment by pmaxted** [comment]
Added in 0.9.17
