### ISSUE TITLE
Build hangs at "Building wheel for celerite2 (PEP 517)"

### ISSUE THREAD

**Issue by bmorris3** [pmaxted/pycheops#170]
With the latest version of pycheops, I'm having trouble upgrading due to celerite2, which hangs on install via `pip` at the following message: 
```
Building wheels for collected packages: celerite2
  Building wheel for celerite2 (PEP 517)
```
Anybody have a fix?

Thanks!

**Comment by ThomasGWilson** [comment]
Hi Brett,

Fortunately this is a known issue, try following these steps:

Installation fails with "ERROR: Could not build wheels for celerite2 which use PEP 517 and cannot be installed directly"

    This error message may appear when upgrading to pycheops version 0.9.1 or later. The working solution is to install celerite2 prior to installing/ updating pycheops using:

    git clone --recursive https://github.com/dfm/celerite2.git

    cd celerite2

    python -m pip install celerite2==0.0.1rc1

Cheers,

Tom

**Comment by bmorris3** [comment]
Thanks! I get the same problem on the last command. 

It seems that I can run `python setup.py install` to successfully install celerite, and then I can simply `pip install --upgrade pycheops`. Perhaps we should tweak the README?
