### ISSUE TITLE
BIC and AIC computation

### ISSUE THREAD

**Issue by odemangeon** [pmaxted/pycheops#177]
I believe that there is a mistake in the computation of the BIC and the AIC made in Dataset.emcee_sampler
In both cases the maximum of the posterior probability is used when it should be the maximum of the likelihood.
Ref for the AIC criterion: http://www.stat.tamu.edu/~suhasini/teaching613/akaike74.pdf

**Comment by pmaxted** [comment]
Fixed in version 0.9.7
