### ISSUE TITLE
get_lightcurve: filtering data also by positive flux values

### ISSUE THREAD

**Issue by Bonfanti88** [pmaxted/pycheops#195]
Dear Pierre,
I may suggest to replace the line of code in dataset.py:
ok = (table['EVENT'] == 0) | (table['EVENT'] == 100)
with
ok = (((table['EVENT'] == 0) | (table['EVENT'] == 100)) & (table['FLUX']>0))
to filter the input data.

In fact, it may happen that a few records have negative flux values, despite being flagged with EVENT=0 or EVENT=100.
It's true that one can a posteriori remove outliers with clip_outliers, but the mean computed there would be influenced by the presence of negative flux values and the rejection won't be completely satisfactory.
As we don't want negative flux values in any case, I think it's worth to have this condition specified since the beginning.

Regards,
Andrea

**Comment by pmaxted** [comment]
Added in version 0.9.8
