### ISSUE TITLE
Take into account eccentricity and argument of pericenter in the parameters

### ISSUE THREAD

**Issue by lucaborsato** [pmaxted/pycheops#199]
I am wondering if it would possible to take into account the term due to the eccentricity and the argument of pericenter in the fitting parameters such as the impact parameter b and the transit duration W.
The term has been described in
[Winn 2010](https://ui.adsabs.harvard.edu/abs/2010exop.book...55W/abstract)
and in
[Kipping 2010](https://ui.adsabs.harvard.edu/abs/2010MNRAS.407..301K/abstract).

**Comment by pmaxted** [comment]
This is not feasible to implement because of the complex relationships between D, W, b, f_c, f_s and there priors. 
See Kipping  2014MNRAS.440.2164K if you need to convert between the transit width and impact parameter assuming/ignoring the eccentricity.
