### ISSUE TITLE
dfdsmear Bug

### ISSUE THREAD

**Issue by mis-95** [pmaxted/pycheops#207]
Fitting of EBLM transit with an all-zero smear array fitted dfdsmear as a decorrelation parameter with a significant Bayes factor. This in turn led to a MultiVisit MC fit with dfdsmear leading to infinite values.

**Comment by pmaxted** [comment]
Dataset will now raise an error message if lmfit_transit or lmfit_eclipse include decorrelation against parameters with zero range.
