### ISSUE TITLE
Cannot download data from DACE

### ISSUE THREAD

**Issue by delinea** [pmaxted/pycheops#215]
DACE seems to have change its API.
When trying to download data with `Dataset(file_key)`, the following Exception occurs:
`TypeError: download() got an unexpected keyword argument 'output_full_file_path'`

The issue is raised in the file **pycheops/dataset.py** (lines 327-329).
One can temporarily fix it by replacing
```
Cheops.download(file_type,
    filters={'file_key':{'contains':file_key}},
    output_full_file_path=str(tgzPath))
```
with
```
try:
    Cheops.download(file_type,
        filters={'file_key':{'contains':file_key}},
        output_full_file_path=str(tgzPath))
except TypeError:
    import os
    Cheops.download(file_type,
        filters={'file_key':{'contains':file_key}},
        output_directory=os.path.dirname(str(tgzPath)),
        output_filename=os.path.basename(str(tgzPath)))
```

**Comment by pmaxted** [comment]
Fixed in 0.9.10 - thanks.
