### ISSUE TITLE
Analysis of non-CHEOPS data with pycheops

### ISSUE THREAD

**Issue by lucaborsato** [pmaxted/pycheops#217]
Dear Pierre,
it would be interesting to implement a Dataset for the data coming from different telescope/mission, such as Kepler/K2 and TESS.
SingleVisit:
read fits or txt file with time, flux, flux_err, diagnostics (custom or pre-defined list with 0 values if not needed)
possibility to specify to compute LD coefficients for the correct filter
MultiVisit:
load SingleVisit analysis and automatically add LD coefficients for filters different from CHEOPS
Best,
Luca

**Comment by pmaxted** [comment]
See https://github.com/Jayshil/pycdata
