### ISSUE TITLE
SWEET-cat Identifier MultiVisit

### ISSUE THREAD

**Issue by mis-95** [pmaxted/pycheops#242]
Currently when inputting identifiers into MultiVisit such as:

id_kws={'match_arcsec':None}
M = MultiVisit('EBLM_J2359+44', ident='J235929.73+444031.1', id_kws=id_kws)

an error message will occur unlike in previous versions:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 168: invalid continuation byte

**Comment by pmaxted** [comment]
Fixed in 0.9.17
