### ISSUE TITLE
Error using StarProperties

### ISSUE THREAD

**Issue by ChickenWithBeans** [pmaxted/pycheops#252]
Hi, Im having some trouble when calling the StarProperties function, which gives me the following error:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 168: invalid continuation byte

I am attempting to run the KELT-11b example using jupyter notebook on a MacOS, It used to work during the first tries however it doesn't anymore, when pycheops was updated.

**Comment by pmaxted** [comment]
Please try upgrading to version 1.0.2 from github to see if this fixes the problem

`pip install --upgrade git+https://github.com/pmaxted/pycheops.git 
`
