### ISSUE TITLE
Backend is being reset in multivisit when burn-in is done

### ISSUE THREAD

**Issue by tundeakins** [pmaxted/pycheops#263]
https://github.com/pmaxted/pycheops/blob/1878ecb613108b45eb02306cb7b2656b58ddfefe/pycheops/multivisit.py#L821

to use backend to restart from last position, burn-in should be ignored if iteration is 0.

```
if iteration == 0:
    pos,_,_,_ = sampler.run_mcmc(pos, kwargs['burn'], store=False, skip_initial_state_check=True, progress=progress)
    sampler.reset()
```

**Comment by pmaxted** [comment]
Fixed in 1.0.5
