### ISSUE TITLE
Typos in output of dataset.get_lightcurve

### ISSUE THREAD

**Issue by andreafortier** [pmaxted/pycheops#265]
Hi Tom and Pierre, 
I wanted to inform you about two "typos" I found when running the jupyter notebook.
Some of the information printed as output of dataset.get_lightcurve is not entirely correct.
For example, the aperture radius seems to be printed as an integer. I get the value 30 arcsec for a case where the aperture is actually 29.5 and 22 when it is 22.5. Another thing I noticed is that the median background is printed with units of e-/px. It should be the integrated background in the whole aperture (so electrons only).
Cheers, 
Andrea

**Comment by andreafortier** [comment]
Another comment: in the diagnostic plots D.diagnostic_plot() the flux is not in ADU but in e- (Y axis labels should say Flux in electrons)

**Comment by pmaxted** [comment]
Fixed in 1.0.5
