### ISSUE TITLE
T_EFF header information not stored in Dataset

### ISSUE THREAD

**Issue by Broeg** [pmaxted/pycheops#266]
Dear Pierre,

it would be good to also read the effective temperature besides the SpTy from the header of the LC fits file. The Teff is actually used by the DRP to pick the correct FF combination. The SpTy, however, is not really relevant. 

To my understanding all that needs to be done is adding one line:

 `       self.teff = hdr['T_EFF']`

in line 402 of dataset.py so that the code section reads:

```        
        if 'MAG_G' in hdr:
            self.gmag = hdr['MAG_G'] 
            self.e_gmag = hdr['MAG_GERR'] 
        else:
            self.gmag =None
        self.teff = hdr['T_EFF']
        self.spectype = hdr['SPECTYPE']
        self.nexp = hdr['NEXP']
```
 Kind regards,
Chris

**Comment by pmaxted** [comment]
Added in 1.0.5 but note that the T_EFF header keyword is not available in older archive FITS files so this attribute will not always be available.

**Comment by Broeg** [comment]
Dear Pierre

thanks a lot! Indeed for older DRP versions you might indeed be right. After reprocessing the Teff will certainly always be present.

Kind regards,
Chris
