### ISSUE TITLE
Issue thread start: lmfit_transit pushing ramp coefficient to prior bounds

### ISSUE THREAD

**Issue by ThomasGWilson** [pmaxted/pycheops#268]
For a couple of recent observations of TOI-1054 (CH_PR100024_TG012203_V0200) and TOI-1774 (CH_PR100024_TG015001_V0200) there appears to be subtle and not-so-subtle ramps to look similar to ramp-like features due to temperature changes that we've seen in visits of other targets.

For the TOI-1054 visit, I have used the PSF SCALPELS approach and corrected the ramp so it appears that it is due to PSF shape changes. However when using correct_ramp() and then including deltaT in the linear model for a lmfit_transit() the ramp coefficients for both visits push up against the prior bounds that are given. In fact, for the TOI-1054 visit it appears that the coefficient should be the opposite sign that the fitted value from pycheops.

I haven't seen this in other visits or in other systems, so it appears uncommon, but now that there are two cases it might be good to look into. Andrew, Juan, and Luisa know more about the individual visits.

**Comment by tundeakins** [comment]
@ThomasGWilson  what priors are you using for the ramp. it appears the ramp coefficients are in ppm, so putting (-1,1) for instance will imply (-1,1) ppm which could explain why the results push against the very low bounds.

**Comment by pmaxted** [comment]
No change required.
