### ISSUE TITLE
not needed line in multivisit.py?

### ISSUE THREAD

**Issue by lucaborsato** [pmaxted/pycheops#271]
Hi Pierre,
I have found that there is this line:
```
lc_fits.append(mod)
```
at line `1029` of the `multivisit.py` file.
I cannot find the variable `lc_fits` in the `multivisit.py`, nor in all other `pycheops` files.
Has it been left on purpose?

**Comment by lucaborsato** [comment]
Perfect!
Thanks!

**Comment by pmaxted** [comment]
Fixed in 1.0.8.
