### ISSUE TITLE
log rho potential issues

### ISSUE THREAD

**Issue by sousasag** [pmaxted/pycheops#276]
Hi,

I notice that the log rho in star properties is computed using the Moya 2018 relation with the spectroscopic logg listed in sweet-cat.
Given that the spectroscopic log g is not the best reliable parameter in sweet-cat I suggest two alternatives:
1- Use the mass and radius (estimated from Torres calibration in sweet-cat) to get the log rho.
2- Instead of the spectroscopic logg for teh Moya relation but use the logg_gaia (Trigonometric value) listed in sweet-cat instead.

Cheers,
Sérgio

**Comment by pmaxted** [comment]
Thanks. Fixed in 1.0.10
