### ISSUE TITLE
dataset.aperture_scan() throws an error if the LC has been loaded with "RINF" aperture

### ISSUE THREAD

**Issue by Broeg** [pmaxted/pycheops#291]
In order not to throw an error, I had to change the loaded aperture to a different one from RINF.

**Comment by pmaxted** [comment]
What is the error if you choose RINF?

**Comment by Broeg** [comment]
Hi Pierre

 

Sorry for the confusion. I tried to reproduce the error but it failed. The same notebook now runs with RINF as activated light curve. Before I got an error like it is not finding the requested aperture or looking for an aperture that does not exist. Can’t remember the exact error. Now it works. No idea what I did wrong last time. Ticket can be closed…

 

Chris
