### ISSUE TITLE
ImportError: cannot import name 'int' from 'numpy'

### ISSUE THREAD

**Issue by suman-exo** [pmaxted/pycheops#292]
This is the error after numpy is updated.

**Comment by pmaxted** [comment]
Please provide the full error message to help me find exactly where this error is raised.
Thanks,
 -Pierre

**Comment by suman-exo** [comment]
https://github.com/pmaxted/pycheops/blob/fae2e128fa95e22c2a73f6c8c6614da0ef533600/pycheops/instrument.py#L36

**Comment by suman-exo** [comment]
Apparently, np.int was deprecated for some time now.
https://numpy.org/devdocs/release/1.20.0-notes.html

**Comment by pmaxted** [comment]
Thanks.
Please try upgrading to 1.0.17 from github and let me know of this fixes the issue.
`pip install git+https://github.com/pmaxted/pycheops/ --upgrade
`
-Pierre

**Comment by suman-exo** [comment]
Thanks, that fixed the issue.
