### ISSUE TITLE
Examples do not work

### ISSUE THREAD

**Issue by MrBudgens** [pmaxted/pycheops#39]
I've installed pycheops using pip and found that the examples don't work properly. Running "make_xml_files NonTimeCriticalOnly.csv" causes:

ValueError: Nearest Gaia DR2 source does not match input ID

The cause seems to be that the test in line 492 is comparing a string with an int64. Changing that line to cast to a string allows the test to pass.

**Comment by pmaxted** [comment]
Cannot replicate so unclear which variable should be cast to a string.
Please submit a push request with the change required or reply here with the new version of this line. 
Thanks,
 -Pierre

**Comment by MrBudgens** [comment]
I'm very new to github so don't yet know how to do a pull request.

I changed line 492 to read:

if str(row['Old_Gaia_DR2']) != str(DR2Table['source_id'][idx]):

And a similar change was required to line 497.

In case it helps, I'm using python 3.6.8 via Anaconda on Windows 10, with all packages updated via conda before installing pycheops.

**Comment by pmaxted** [comment]
Should now be fixed. New version (0.1.5) merged into master branch on GitHub and upload to pypi. Please re-install (pip install pycheops --upgrade) and let me know if the examples now work.
Thanks, 
-Pierre

**Comment by MrBudgens** [comment]
Confirmed. Thank you!
