### ISSUE TITLE
Retrieving raw data

### ISSUE THREAD

**Issue by alphapsa** [pmaxted/pycheops#53]
It could be useful to be able to retrieve raw data (including house keeping, imagettes etc) in addition to the pipeline reduced data. I am not sure this is entirely within the scope of pycheops, but I can see it being useful in some cases when one would want to e.g. inspect the raw data or do an alternative reduction / analysis.

**Comment by pmaxted** [comment]
Download from DACE was added in version 0.4.0 for Dataset(). This is slow so this may change in future versions, but the option to download everything will be kept.
