### ISSUE TITLE
dataset.from_simulation fails when there is no imagette in the dataset (texp>=22.65s)

### ISSUE THREAD

**Issue by ldelrez** [pmaxted/pycheops#61]
dataset.from_simulation fails when there is no imagette in the dataset with the error message 'No imagette file in zip file'. However, this will happen for any exposure time higher than 22.65s for which the stacking order is 1 (no imagettes are produced in this case, all the information is contained in the subarray images). I guess the imagette file should be replaced by the subarray file in this case?

**Comment by pmaxted** [comment]
Fixed in version 0.6.1
