### ISSUE TITLE
Output rho_star in rho_sun from StarProperties?

### ISSUE THREAD

**Issue by lucaborsato** [pmaxted/pycheops#79]
Is it possible to have also the stellar density in rho_sun (not the log) from StarProperties? Thank you.

**Comment by pmaxted** [comment]
Why is this needed? The value can be accessed/printed very easily, e.g.

>>> from pycheops import StarProperties
>>> s = StarProperties('KELT-11')
>>> rho = 10**s.logrho
>>> print('{:0.3f}'.format(rho))
0.068+/-0.012

**Comment by lucaborsato** [comment]
I had issue converting from logrho within StarProperties to physical units, e.g. errors greater than density itself. Sorry to bother.

**Comment by lucaborsato** [comment]
I have found my error, sorry again. Closing.
