### ISSUE TITLE
feature request: add metadata

### ISSUE THREAD

**Issue by Broeg** [pmaxted/pycheops#93]
It would be good to add the metadata (e.g. CCD and ADC temperatures & bias voltages) also to the dataset object. I expect there to be correlations to the gain and hence the reported flux.

**Comment by pmaxted** [comment]
Hi Chris,

 can you be more specific about which columns you want from which tables in which FITS file(s)?

**Comment by ThomasGWilson** [comment]
Just to revive this following the ramp analysis findings ,I think it could be good to take "thermFront2" from the metadata of *_SCI_COR_Lightcurve_* . Although it might be worth to just save the whole metadata table to a dataset object so users can have access to all:

['UTC_TIME', 'MJD_TIME', 'BJD_TIME', 'CTYPE1', 'CRPIX1', 'CRVAL1', 'CUNIT1', 'CTYPE2', 'CRPIX2', 'CRVAL2', 'CUNIT2', 'CD1_1', 'CD1_2', 'CD2_1', 'CD2_2', 'LOS_TO_SUN_ANGLE', 'LOS_TO_MOON_ANGLE', 'CE_COUNTER', 'CE_INTEGRITY', 'HK_VOLT_FEE_VOD', 'HK_VOLT_FEE_VRD', 'HK_VOLT_FEE_VOG', 'HK_VOLT_FEE_VSS', 'HK_TEMP_FEE_CCD', 'HK_TEMP_FEE_ADC', 'HK_TEMP_FEE_BIAS', 'ADC_N5V', 'ADC_TEMP1', 'thermAft_1', 'thermAft_2', 'thermAft_3', 'thermAft_4', 'thermFront_1', 'thermFront_2', 'thermFront_3', 'thermFront_4', 'BIAS', 'RON']

**Comment by pmaxted** [comment]
Done - added in version 0.9.7
